name: "Mindful Care Infra - stage Terraform Workflow"

permissions:
  id-token: write
  contents: read

on:
  push:
    paths:
      - 'infra/stage/**'
    branches:
      - main

env:
  AWS_DEFAULT_REGION: us-east-2

jobs:
  checkov_security_scan:
    name: 'Security Scan with Checkov'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install & Run Checkov
      run: |
        pip install checkov
        checkov -d .
      continue-on-error: true

    # This message is optional and can be uncommented if desired
    # - name: Scan Completion Message
    #   run: echo "Scan complete! Onward to infrastructure as code greatness! 🖖🏻"

  terraform_workflow:
    needs: checkov_security_scan
    name: "Terraform: Init, Validate, Plan, Apply"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::560668774271:role/mc-stage-github-actions-role
        aws-region: us-east-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: |
        cd infra/stage
        terraform init -backend-config="bucket=mc-stage-terraform-state" \
                      -backend-config="region=us-east-2" \
                      -backend-config="dynamodb_table=mc-stage-tf-statelock" \
                      -backend-config="key=mc-stage-terraform.tfstate"

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: |
        cd infra/stage
        terraform plan -var-file=stage.tfvars -no-color -out=tfplan

    - name: Apply Terraform Changes
      run: |
        cd infra/stage
        terraform apply -auto-approve -var-file=stage.tfvars

    - name: Deployment Completion Message
      run: echo "Deployment unlocked! The matrix has been updated with our latest blueprints🔵🖨️"